services:
  server:
    build:
      context: .

    restart: unless-stopped

    ports:
      - ${MINECRAFT_PORT:-19132}:19132/udp

    environment:
      - EULA=TRUE

    volumes:
      - ./data:/data
