services:
  server:
    image: makeinspires/minecraft-edu-server:latest

    restart: unless-stopped

    ports:
      - ${MINECRAFT_PORT:-19132}:${MINECRAFT_PORT:-19132}/udp

    environment:
      - EULA=TRUE

    volumes:
      - ./data:/data
