services:
  ues:
    image: makeinspires/minecraft-edu-server:latest

    restart: unless-stopped

    ports:
      - 19132:19132/udp

    environment:
      - EULA=TRUE

    volumes:
      - ./ues-data:/data

  mamaroneck:
    image: makeinspires/minecraft-edu-server:latest

    restart: unless-stopped

    ports:
      - 19133:19133/udp

    environment:
      - EULA=TRUE
      - SERVER_PORT=19133

    volumes:
      - ./mamaroneck-data:/data

  brooklyn:
    image: makeinspires/minecraft-edu-server:latest

    restart: unless-stopped

    ports:
      - 19134:19134/udp

    environment:
      - EULA=TRUE
      - SERVER_PORT=19134

    volumes:
      - ./brooklyn-data:/data

  darien:
    image: makeinspires/minecraft-edu-server:latest

    restart: unless-stopped

    ports:
      - 19135:19135/udp

    environment:
      - EULA=TRUE
      - SERVER_PORT=19135

    volumes:
      - ./darien-data:/data

  chappaqua:
    image: makeinspires/minecraft-edu-server:latest

    restart: unless-stopped

    ports:
      - 19136:19136/udp

    environment:
      - EULA=TRUE
      - SERVER_PORT=19136

    volumes:
      - ./chappaqua-data:/data
